Repository jemmia-diamond/jemmia-priority-server, pull requests merged in 2025-08, with the labels that each got.

#22 chore: remove Sentry performance monitoring
  src/main.ts
Labels: Review effort 1/5

#23 Fix/zaloauth/phone
  src/auth/auth.service.ts
  src/zalo-otp/zalo-otp.controller.ts
  src/zalo-otp/zalo-otp.service.ts
Labels: Review effort 2/5

#25 fix user entity
  src/user/entities/user.entity.ts
Labels: Review effort 1/5

#18 Add customer type affiliate
  src/app.module.ts
  src/auth/auth.service.ts
  src/crm/crm.service.spec.ts
  src/crm/crm.service.ts
  src/customer-rank/customer-rank.service.ts
  src/haravan/constants/gateway-type.const.ts
  src/haravan/enums/payment-type.enum.ts
  src/haravan/haravan.service.ts
  src/order/constants/payment-commision.ts
  src/order/entities/order.entity.ts
  src/order/enum/order-type.enum.ts
  src/order/enum/payment-status.enum.ts
  src/order/order.service.ts
  src/user/enums/user-role.enum.ts
  src/user/user.service.ts
Labels: Review effort 4/5
